# fundamentals

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


# Intro to tensors

## Creating tensors

In [8]:
# scalars
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # check dimn of tensor

0

In [ ]:
scalar.item() # get scalar back as a python int

7

In [21]:
# vector
vector=torch.tensor([[7,7,8],[7,7,8]])
vector

tensor([[7, 7, 8],
        [7, 7, 8]])

In [18]:
vector.ndim

2

In [22]:
vector.shape

torch.Size([2, 3])

In [23]:
# matrix
matrix=torch.tensor([[7,8],
                     [9,10]])
matrix


tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
matrix.ndim

2

In [26]:
matrix[1]

tensor([ 9, 10])

In [27]:
matrix.shape

torch.Size([2, 2])

In [28]:
# tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [29]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape 
# will give (no of matrices, no of rows, no of cols)

torch.Size([1, 3, 3])

In [33]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [34]:
TENSOR[0][0]

tensor([1, 2, 3])

In [35]:
TENSOR[0][1]

tensor([3, 6, 9])

In [36]:
TENSOR[0][2]

tensor([2, 4, 5])

# RANDOM TENSORS

In [44]:
# CREATE A RANDOM TENSOR OF SIZE (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5470, 0.9591, 0.6824, 0.3918],
        [0.7485, 0.9109, 0.8292, 0.2235],
        [0.0734, 0.1663, 0.6840, 0.0034]])

In [46]:
random_tensor.ndim

2

In [49]:
# create a random tensor with shape simialr to a image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) # height,width,color channel (r,g,b)
random_image_size_tensor.shape,random_image_size_tensor.ndim
random_image_size_tensor

tensor([[[0.5829, 0.3958, 0.5941,  ..., 0.3885, 0.0269, 0.0635],
         [0.2024, 0.3605, 0.5476,  ..., 0.2180, 0.0189, 0.9221],
         [0.9532, 0.7004, 0.9913,  ..., 0.8826, 0.5728, 0.8770],
         ...,
         [0.8412, 0.1932, 0.4462,  ..., 0.9982, 0.4056, 0.1853],
         [0.4140, 0.8422, 0.0754,  ..., 0.7965, 0.0158, 0.9417],
         [0.3431, 0.3953, 0.9937,  ..., 0.4471, 0.8225, 0.6544]],

        [[0.5598, 0.1345, 0.2448,  ..., 0.3725, 0.7192, 0.3494],
         [0.6001, 0.3809, 0.5205,  ..., 0.3016, 0.9772, 0.5545],
         [0.4513, 0.3892, 0.8048,  ..., 0.4000, 0.9506, 0.4279],
         ...,
         [0.9290, 0.6590, 0.5497,  ..., 0.3610, 0.3744, 0.5788],
         [0.4930, 0.9910, 0.1465,  ..., 0.7459, 0.3674, 0.6415],
         [0.3607, 0.0134, 0.9547,  ..., 0.0069, 0.0647, 0.1470]],

        [[0.0293, 0.4348, 0.4104,  ..., 0.0062, 0.0982, 0.1227],
         [0.6729, 0.7587, 0.9458,  ..., 0.8508, 0.8266, 0.9324],
         [0.2310, 0.4043, 0.9486,  ..., 0.7946, 0.5528, 0.

# zeros and ones

In [ ]:
# create a tensor  of all zeros
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [52]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
# create a tensor  of all ones
ones=torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [54]:
ones.dtype

torch.float32

# CREATING A TENSOR OF RANGE

In [56]:
# use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# DEALING WITH TENSOR DATATYPES

In [72]:
# float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device="cpu", #  
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [73]:
float_32_tensor.dtype

torch.float32

In [74]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# TENSOR ATTRIBUTES

In [75]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [76]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [77]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

# Getting info from tensors

### 1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype 
### 2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
### 3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [79]:
# create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.2394, 0.4362, 0.0226, 0.4935],
        [0.8178, 0.5373, 0.8326, 0.4453],
        [0.1827, 0.5084, 0.6729, 0.0207]])

In [81]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of Tensor : {some_tensor.device}")

tensor([[0.2394, 0.4362, 0.0226, 0.4935],
        [0.8178, 0.5373, 0.8326, 0.4453],
        [0.1827, 0.5084, 0.6729, 0.0207]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of Tensor : cpu


# MANIPULATING TENSORS

### Tensor opertions include:
### Addition
### Subtraction
### Multiplication (element-wise)
### Division
### Matrix mutiplication

In [97]:
# create a tensor
tensor=torch.tensor([1,2,3])
# add
tensor+10


tensor([11, 12, 13])

In [98]:
# multiply by 10
tensor*10

tensor([10, 20, 30])

In [99]:
tensor

tensor([1, 2, 3])

In [100]:
# subtract 10
tensor-10

tensor([-9, -8, -7])

In [101]:
# inbuilt functions
torch.mul(tensor,30)

tensor([30, 60, 90])

# MATRIX MULTIPLICATION

In [102]:
# ELEMENT WISE
tensor*tensor

tensor([1, 4, 9])

In [103]:
# matrix mult
torch.matmul(tensor,tensor)

tensor(14)

In [104]:
torch.matmul(torch.rand(3,10),torch.rand(10,3))

tensor([[3.3673, 3.0495, 1.7264],
        [2.8177, 2.8562, 1.7241],
        [2.2321, 2.3800, 1.5100]])

# TENSOR AGGREGATIONS

In [107]:
# CREATE A TENSOR
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [109]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [110]:
# find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [113]:
# find the mean
# torch.mean(x) # gives error
torch.mean(x.type(torch.float32))

tensor(45.)

In [114]:
# find the sum
torch.sum(x)

tensor(450)

# position of min max

In [ ]:
x.argmin() # find the pos in tensor that has min value with argmin and returns the index of target tensor

tensor(0)

In [ ]:
x.argmax() # return the index of arg max tensor value

tensor(9)

In [118]:
x[9]

tensor(90)

# RESHAPING , STACKING , SQUEEZING AND UNSQUEEZING 


### Reshaping, stacking, squeezing and unsqueezing tensors
### • Reshaping - reshapes an input tensor to a defined shape
### • View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
### • Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
### ⚫ Squeeze - removes all 1 dimensions from a tensor
### ⚫ Unsqueeze - add a 1 dimension to a target tensor
### • Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

# SELECTING DATA USING INDEXING

In [1]:
# create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# indexing on this new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
# index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [4]:
# index on the inner most bracket
x[0][0][0]

tensor(1)

### get all values of 0th and 1st dimensions but only of index 1 and 2nd dimension

In [5]:
x[:,:,1]

tensor([[2, 5, 8]])

### get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension

In [6]:
x[:,1,1]

tensor([5])

# PYTORCH AND NUMPY

### PyTorch tensors & NumPy

### NumPy is a popular scientific Python numerical computing library.

### And because of this, PyTorch has functionality to interact with it.

### • Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)

### • PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [7]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

### Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

### However, many PyTorch calculations default to using float32.

### So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

### Because we reassigned tensor above, if you change the tensor, the array stays the same.

In [11]:
# Change the array, keep the tensor
array = array + 1
print(array, tensor)

print(f"And if you want to go from PyTorch tensor to NumPy array, you can call tensor.numpy().")

[ 5.  6.  7.  8.  9. 10. 11.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
And if you want to go from PyTorch tensor to NumPy array, you can call tensor.numpy().


# REPRODUCBILITY

### In short:

### start with random numbers -> tensor operations -> try to make better (again and again and again)

In [12]:
import torch

# create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8904, 0.4693, 0.4663, 0.8718],
        [0.6672, 0.0329, 0.0123, 0.6049],
        [0.9894, 0.5180, 0.9386, 0.2727]])
tensor([[0.9051, 0.8747, 0.8711, 0.6149],
        [0.1731, 0.1535, 0.1520, 0.5205],
        [0.9314, 0.2626, 0.2395, 0.3338]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [17]:
# lets make random but reproducible tensors
import torch

# seed the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
