# First Real Hugging Face Code

In [7]:
from transformers import AutoTokenizer

## What we used to do 
What Exists On Hugging Face?

Thousands of pretrained models.

Examples:

GPT-2
Llama 3
Mistral 7B
BERT
T5
What We Used To Do

In GPT-from-scratch:

stoi
itos
encode
decode

Everything was built manually.

What Hugging Face Does

Suppose somebody already trained GPT-2.

They upload:

Tokenizer
Vocabulary
BPE Rules
Model Weights
Configuration
Documentation

to Hugging Face.

You simply download it.

## Cell 2 : Load GPT-2 Tokenizer

In [8]:
tokenizer=AutoTokenizer.from_pretrained(
  "gpt2"
)

## Cell 3 : Basic Encoding

In [3]:
text="I love transformers"
token_ids=tokenizer.encode(text)
print(token_ids)

[40, 1842, 6121, 364]


## Cell 4 : Decode

In [4]:
decoded=tokenizer.decode(
  token_ids
)
print(decoded)

I love transformers


## Cell 5 : See Actual Tokens

In [5]:
text = "transformers are amazing"

tokens = tokenizer.tokenize(text)

print(tokens)


# What Does Ġ Mean?

# GPT-2 uses:

# Ġ

# to indicate:

# Leading Space

# So:

# Ġare

# means:

# " are"

['transform', 'ers', 'Ġare', 'Ġamazing']


In [6]:
text = """
Artificial Intelligence and Machine Learning
"""

print(
    tokenizer.tokenize(text) # tokenize return actual bpe tokens
)

['Ċ', 'Art', 'ificial', 'ĠIntelligence', 'Ġand', 'ĠMachine', 'ĠLearning', 'Ċ']


# Lesson 2 : AutoModel

The IDs cannot directly enter a transformer.

Remember our GPT implementation:

Token IDs

Embedding Layer

Position Embeddings

Attention

Feed Forward

Hidden States

AutoModel gives us access to:

Embeddings
Hidden States
Transformer Outputs

but NOT text generation.

## CELL1

In [7]:
from transformers import AutoTokenizer
from transformers import AutoModel

## CELL2-> LOAD GPT2

In [8]:
tokenizer = AutoTokenizer.from_pretrained(
    "gpt2"
)

model = AutoModel.from_pretrained(
    "gpt2"
)

# What Gets Downloaded?

# Tokenizer:

# Vocabulary
# BPE Rules

# Model:

# Weights
# Configuration
# Architecture

# This is basically:

# Your GPT From Scratch

# except trained by OpenAI.

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

## CELL3-> PREPARE INPUT

In [9]:
text = "I love transformers"

inputs = tokenizer(
    text,
    return_tensors="pt"
)

print(inputs)

# What Is return_tensors="pt" ?

# Without:

# tokenizer.encode()

# returns:

# [40,1842,6121]

# Python list.

# With:

# return_tensors="pt"

# returns:

# tensor([[40,1842,6121]])

# PyTorch tensor.

{'input_ids': tensor([[  40, 1842, 6121,  364]]), 'attention_mask': tensor([[1, 1, 1, 1]])}


## Cell 4

Pass through model.

In [10]:
outputs = model(
    **inputs
)
print(outputs)
print(
    outputs.last_hidden_state.shape
)
# This is the final Transformer output.

# So with:

# AutoModel

# you stop at:

# Input Text
 
# Tokenizer
 
# Input IDs
 
# Embeddings
 
# Transformer
 
# last_hidden_state



BaseModelOutputWithPastAndCrossAttentions(last_hidden_state=tensor([[[-0.0796, -0.0654, -0.0842,  ..., -0.1442, -0.0456,  0.0142],
         [ 0.0757, -0.0351, -0.4318,  ..., -0.3136,  0.1932,  0.1943],
         [ 0.0283, -0.4037, -0.7253,  ...,  0.0855,  0.4148, -0.2121],
         [-0.0140, -0.1136, -1.8086,  ..., -0.0636,  0.2788,  0.3782]]],
       grad_fn=<ViewBackward0>), past_key_values=DynamicCache(layers=[DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer]), hidden_states=None, attentions=None, cross_attentions=None)
torch.Size([1, 4, 768])


## Cell 5

Inspect one token.

In [11]:
print(
    outputs.last_hidden_state[0,0]
)

# This is the learned representation for:

# "I"

# after passing through the transformer.


# Important Connection To Previous Phases

# Earlier:

# Phase 3

# Token Embedding
# ↓
# Attention
# ↓
# FFN
# ↓
# Hidden State

# Now:

# outputs.last_hidden_state

# IS that hidden state.

# You're looking at the actual output of a pretrained GPT-2 transformer.

tensor([-7.9628e-02, -6.5353e-02, -8.4245e-02, -3.3673e-02, -7.5765e-02,
        -2.0510e-01, -4.3776e-01, -1.0283e-01, -1.2901e-01,  1.5545e-02,
         2.4748e-01,  3.5613e-04, -9.3426e-02,  3.7775e-02, -9.4859e-02,
        -2.7128e-02, -3.1572e-01, -1.4446e-04,  2.6252e-02,  1.2470e-01,
         1.2706e-01, -9.9013e-02, -3.6124e-01, -6.9349e-02,  8.9790e-03,
         1.3573e-01, -2.4174e-01, -2.5611e-01,  9.7498e-02, -1.9493e-01,
         9.0376e-02, -1.9830e-01, -2.1238e-01, -3.3380e-01, -7.5663e-03,
        -5.6572e-02,  2.9477e+01,  1.0314e-01,  4.7633e-02,  1.1722e-01,
        -2.7945e-02, -1.5228e-02, -7.7770e-02, -3.3820e-01, -1.9241e-01,
         7.3541e-02, -1.2433e-01, -5.6931e-02, -3.6314e-01,  4.3728e-01,
        -8.1863e-02, -1.0636e-03, -1.3351e-01, -1.1513e-01, -4.5608e-02,
         3.3211e-01,  1.9618e-03, -1.0413e-01, -1.7054e-01, -6.8189e-02,
         2.1270e-01, -2.1292e-02, -8.7563e-02, -2.5195e-01, -1.0435e+00,
        -3.7328e-02, -1.1853e-01, -1.6257e-01, -2.7

#### Remember:

Tokenizer
↓
Token IDs
↓
Transformer
↓
Hidden States

AutoModel stops here.

It does NOT generate text.

# Phase 5 - Lesson 3
AutoModelForCausalLM

This is where everything from GPT implementation comes together.

Problem

Suppose:

outputs = model(**inputs)

We get:

outputs.last_hidden_state

Shape:

(1,3,768)

But where are:

Vocabulary Scores?

Next Token Predictions?

Generation?

Not available.

## Cell 1

In [12]:
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM
)

## Cell 2

Load GPT-2

In [13]:
tokenizer = AutoTokenizer.from_pretrained(
    "gpt2"
)

model = AutoModelForCausalLM.from_pretrained(
    "gpt2"
)

# What Changed?

# Earlier:

# AutoModel

# Now:

# AutoModelForCausalLM

# Meaning:

# Hidden States
# ↓
# LM Head
# ↓
# Vocabulary Logits

# are included.

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

## Cell 3

Prepare Input

In [14]:
text = "I love"

inputs = tokenizer(
    text,
    return_tensors="pt"
)
inputs["input_ids"].shape

torch.Size([1, 2])

## Cell 4

Forward Pass

In [15]:
outputs = model(
    **inputs
)
print(
    outputs.logits.shape
)
print(outputs)

torch.Size([1, 2, 50257])
CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[-39.3085, -39.0101, -41.8375,  ..., -46.9338, -44.9074, -39.5150],
         [-84.4961, -85.0686, -90.6138,  ..., -91.6659, -93.1035, -87.5303]]],
       grad_fn=<UnsafeViewBackward0>), past_key_values=DynamicCache(layers=[DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer]), hidden_states=None, attentions=None, cross_attentions=None)


## Cell 5

Get Last Token Prediction

In [16]:
next_token_logits = outputs.logits[
    :,
    -1,
    :
]
print(next_token_logits)

# Meaning:

# Scores for next token

# after:

# I love

tensor([[-84.4961, -85.0686, -90.6138,  ..., -91.6659, -93.1035, -87.5303]],
       grad_fn=<SelectBackward0>)


## Cell 6

Convert To Probabilities

In [17]:
import torch

probs = torch.softmax(
    next_token_logits,
    dim=-1
)
probs.shape
print(probs)

tensor([[2.4728e-04, 1.3949e-04, 5.4488e-07,  ..., 1.9027e-07, 4.5190e-08,
         1.1897e-05]], grad_fn=<SoftmaxBackward0>)


## Cell 7

Choose Most Likely Token

In [18]:
next_token = torch.argmax(
    probs,
    dim=-1
)
print(next_token) # gives idnex of the largest probablity

tensor([262])


### Decode

In [19]:
print(
    tokenizer.decode(
        next_token
    )
)

# What Just Happened?

# We manually performed:

# Prompt
# ↓
# Tokenizer
# ↓
# Transformer
# ↓
# LM Head
# ↓
# Logits
# ↓
# Softmax
# ↓
# Argmax
# ↓
# Next Token

# Exactly what GPT does.

# But We Don't Usually Do This

# Hugging Face provides:

# generate()

 the


## Cell 8

Text Generation

In [20]:
output = model.generate(
    **inputs,
    max_new_tokens=20
)
print(output.shape)

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


torch.Size([1, 22])


### Decode

In [21]:
generated_text = tokenizer.decode(
    output[0]
)

print(generated_text)

# What Happens Internally?
# I love
# ↓
# Predict Token
# ↓
# Append
# ↓
# Predict Next Token
# ↓
# Append
# ↓
# Repeat

# Exactly like our:

# generate()

# method from GPT-from-scratch.

I love the way you're doing it. I love the way you're doing it. I love the way


# Lesson 4 : Pipelines

Problem

For every model we repeatedly write:

Load Tokenizer

Load Model

Tokenize

Generate

Decode

Lots of boilerplate.

Solution

Hugging Face Pipelines.

Think:

Pipeline
=
Ready-made AI application

# First Pipeline

In [22]:
from transformers import pipeline

## Text Generation Pipeline

In [23]:
generator = pipeline(
    "text-generation",
    model="gpt2"
)

# What Happens Internally?

# Hugging Face automatically does:

# Download Tokenizer
# ↓
# Download Model
# ↓
# Tokenize
# ↓
# Generate
# ↓
# Decode

# All hidden from you.

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

## Generate Text

In [24]:
result = generator(
    "I love artificial intelligence",
    max_new_tokens=30
)

print(result)

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=30) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=T

[{'generated_text': 'I love artificial intelligence, but I really like humans," she said. "I have a very good understanding of how people are interacting with us. It\'s just a really'}]


### Cleaner Output

In [25]:
print(
    result[0]["generated_text"]
)

I love artificial intelligence, but I really like humans," she said. "I have a very good understanding of how people are interacting with us. It's just a really


## Different Pipeline Tasks

This is where Hugging Face becomes powerful.

## Sentiment Analysis

In [26]:
classifier = pipeline(
    "sentiment-analysis"
)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.


Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [27]:
classifier(
    "I dont love learning transformers"
)

# This is NOT a GPT model.

# This is a fine-tuned transformer.

# Remember Phase 4:

# Pretraining
# ↓
# Fine-Tuning

# Sentiment models are examples of:

# Fine-Tuned Models

[{'label': 'NEGATIVE', 'score': 0.9930369257926941}]

### Summarization

In [28]:
# from transformers import pipeline
# summarizer = pipeline(
#     "summarization"
# )
# not working 


## Question Answering

In [29]:
from transformers import pipeline

classifier = pipeline(
    "sentiment-analysis"
)

print(
    classifier(
        "I love transformers"
    )
)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.


Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

[{'label': 'POSITIVE', 'score': 0.9995483756065369}]


# Lesson 5 : Chat Models

In [4]:
from transformers import pipeline

In [5]:
generator = pipeline(
    "text-generation",
    model="gpt2"
)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [6]:
print(
    generator(
        "Explain AI",
        max_new_tokens=50
    )[0]["generated_text"]
)

# Observe:

# Not very chat-like

# Why?

# Because GPT-2 is not instruction tuned.

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=T

Explain AI in a Functional Language

I hope this article covers a broad range of topics that are related to the subject of Artificial Intelligence in a functional language (AI). Artificial Intelligence can be used to understand systems and make decisions in the real world. This article


Today almost nobody deploys:

GPT-2

for assistants.

Instead they use:

Llama-Instruct

Mistral-Instruct

Qwen-Instruct

because those models understand:

Question
↓
Answer

style interactions.

# Lesson 6 : Datasets

## First Import

In [1]:
from datasets import load_dataset

In [2]:
dataset = load_dataset(
    "imdb"
)

## Inspect Dataset

In [3]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})


## Access Training Data

In [4]:
train_dataset = dataset["train"]
print(train_dataset[0])

# Why This Is Useful

# For sentiment analysis:

# Text
# ↓
# Positive/Negative Label

# Exactly what we discussed earlier.

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [5]:
print(train_dataset.features)
print(len(train_dataset))
# Selecting Data
print(train_dataset[:5])


# Later in Fine-Tuning:

# dataset = load_dataset(...)

# becomes:

# trainer.train()

# The model learns from these examples.

{'text': Value('string'), 'label': ClassLabel(names=['neg', 'pos'])}
25000
{'text': ['I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was c

## Dataset Transformation

In [9]:
sample = train_dataset[0]
tokenized = tokenizer(
    sample["text"]
)
print(tokenized)

{'input_ids': [40, 26399, 314, 3001, 327, 47269, 20958, 12, 56, 23304, 3913, 422, 616, 2008, 3650, 780, 286, 477, 262, 10386, 326, 11191, 340, 618, 340, 373, 717, 2716, 287, 15904, 13, 314, 635, 2982, 326, 379, 717, 340, 373, 12000, 416, 471, 13, 50, 13, 17112, 611, 340, 1683, 3088, 284, 3802, 428, 1499, 11, 4361, 852, 257, 4336, 286, 7328, 3177, 366, 3642, 46927, 1, 314, 1107, 550, 284, 766, 428, 329, 3589, 29847, 1671, 1220, 6927, 1671, 11037, 464, 7110, 318, 19254, 1088, 257, 1862, 14023, 10512, 3710, 3706, 44131, 508, 3382, 284, 2193, 2279, 673, 460, 546, 1204, 13, 554, 1948, 673, 3382, 284, 2962, 607, 32649, 507, 284, 1642, 617, 3297, 286, 11648, 319, 644, 262, 2811, 7289, 68, 1807, 546, 1728, 1964, 2428, 884, 355, 262, 10836, 1810, 290, 3234, 2428, 287, 262, 1578, 1829, 13, 554, 1022, 4737, 7602, 290, 8850, 2853, 44908, 286, 29679, 546, 511, 9317, 319, 4819, 11, 673, 468, 1714, 351, 607, 10512, 4701, 11, 28999, 11, 290, 6405, 1450, 29847, 1671, 1220, 6927, 1671, 11037, 2061, 1284

# Lesson 7 : Embedding Models

## Remember:

Similar Meaning
↓
Similar Vectors

Examples:

Cat ≈ Dog

King ≈ Queen

AI ≈ Artificial Intelligence

Suppose:

Sentence 1

I love machine learning
Sentence 2

I enjoy studying AI

Semantically:

Very Similar

Can we use GPT-2 hidden states directly?

Technically:

Yes

Practically:

Not Ideal

Because GPT is optimized for:

Next Token Prediction

not

Semantic Similarity

## First Embedding Model

In [10]:
from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# What Happens?

# Hugging Face downloads:

# Tokenizer

# Transformer

# Weights

# Embedding Head

# This model is specifically trained for:

# Semantic Search

c:\Users\ahlaw\OneDrive\Desktop\PYTORCH\venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ahlaw\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

## Cell 3

Create Embedding

In [15]:
sentence = (
    "I love machine learning"
)

embedding = model.encode(
    sentence
)
print(
    embedding.shape
)

s1 = "I love AI"

s2 = "I enjoy machine learning"

s3 = "Pizza tastes great"
emb1 = model.encode(s1)

emb2 = model.encode(s2)

emb3 = model.encode(s3)

(384,)


## CELL4 COSINE SIMILARITY

In [16]:
from sklearn.metrics.pairwise import (
    cosine_similarity
)
sim12 = cosine_similarity(
    [emb1],
    [emb2]
)

sim13 = cosine_similarity(
    [emb1],
    [emb3]
)

print(sim12)

print(sim13)

[[0.62176245]]
[[0.140354]]
